[build]
builder = "NIXPACKS"
buildCommand = "apt-get update && apt-get install -y nodejs npm && pip install -r requirements.txt && cd frontend && npm install && npm run build"

[start]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"