[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && cd frontend && npm install && npm run build"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
