"""Add personal info fields to passport applications

Revision ID: 38f0c46e90e9
Revises: d19351c44d6c
Create Date: 2025-10-02 22:12:35.029556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f0c46e90e9'
down_revision: Union[str, None] = 'd19351c44d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_celery_task_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_celery_task_id'), 'notifications', ['celery_task_id'], unique=False)
    op.add_column('passport_applications', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('passport_applications', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('passport_applications', sa.Column('date_of_birth', sa.String(length=10), nullable=False))
    op.add_column('passport_applications', sa.Column('place_of_birth', sa.String(length=100), nullable=False))
    op.add_column('passport_applications', sa.Column('nationality', sa.String(length=50), nullable=False))
    op.add_column('passport_applications', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('passport_applications', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('passport_applications', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('passport_applications', sa.Column('residential_address', sa.Text(), nullable=False))
    op.add_column('passport_applications', sa.Column('national_id_number', sa.String(length=20), nullable=True))
    op.add_column('passport_applications', sa.Column('previous_passport_number', sa.String(length=20), nullable=True))
    op.add_column('passport_applications', sa.Column('reason_for_issuance', sa.String(length=20), nullable=False))
    op.add_column('passport_applications', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('passport_applications', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('passport_applications', sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
    op.add_column('passport_applications', sa.Column('travel_purpose', sa.String(length=200), nullable=True))
    op.add_column('passport_applications', sa.Column('intended_travel_date', sa.DateTime(), nullable=True))
    op.add_column('passport_applications', sa.Column('passport_photo_path', sa.String(length=255), nullable=True))
    op.add_column('passport_applications', sa.Column('id_document_path', sa.String(length=255), nullable=True))
    op.add_column('passport_applications', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passport_applications', 'notes')
    op.drop_column('passport_applications', 'id_document_path')
    op.drop_column('passport_applications', 'passport_photo_path')
    op.drop_column('passport_applications', 'intended_travel_date')
    op.drop_column('passport_applications', 'travel_purpose')
    op.drop_column('passport_applications', 'emergency_contact_relationship')
    op.drop_column('passport_applications', 'emergency_contact_phone')
    op.drop_column('passport_applications', 'emergency_contact_name')
    op.drop_column('passport_applications', 'reason_for_issuance')
    op.drop_column('passport_applications', 'previous_passport_number')
    op.drop_column('passport_applications', 'national_id_number')
    op.drop_column('passport_applications', 'residential_address')
    op.drop_column('passport_applications', 'phone')
    op.drop_column('passport_applications', 'email')
    op.drop_column('passport_applications', 'gender')
    op.drop_column('passport_applications', 'nationality')
    op.drop_column('passport_applications', 'place_of_birth')
    op.drop_column('passport_applications', 'date_of_birth')
    op.drop_column('passport_applications', 'last_name')
    op.drop_column('passport_applications', 'first_name')
    op.drop_index(op.f('ix_notifications_celery_task_id'), table_name='notifications')
    op.create_index('idx_notifications_celery_task_id', 'notifications', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###
