"""Add submission location to  passport applications

Revision ID: c6e2571c1b5e
Revises: f1e7569c82ab
Create Date: 2025-10-15 11:31:51.218342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e2571c1b5e'
down_revision: Union[str, None] = 'f1e7569c82ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_applications', sa.Column('submission_location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'passport_applications', 'pickup_locations', ['submission_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passport_applications', type_='foreignkey')
    op.drop_column('passport_applications', 'submission_location_id')
    # ### end Alembic commands ###
