"""Add location awareness to applications and officers

Revision ID: f1e7569c82ab
Revises: 38f0c46e90e9
Create Date: 2025-10-15 10:36:20.409538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e7569c82ab'
down_revision: Union[str, None] = '38f0c46e90e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type first
    appointmenttype = sa.Enum('SUBMISSION', 'COLLECTION', name='appointmenttype')
    appointmenttype.create(op.get_bind(), checkfirst=True)
    
    # Now add the column with the enum type
    op.add_column('pickup_appointments', sa.Column('appointment_type', appointmenttype, nullable=False, server_default='COLLECTION'))
    
    op.add_column('users', sa.Column('assigned_location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'pickup_locations', ['assigned_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_location_id')
    op.drop_column('pickup_appointments', 'appointment_type')
    # ### end Alembic commands ###
